version: '3.8'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexo-blog
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
